#' The application server-side
#' 
#' @param input,output,session Internal parameters for {shiny}. 
#'     DO NOT REMOVE.
#' @import shiny
#' @import shinyjs
#'
#' @noRd
#' 

app_server <- function( input, output, session ) {
  
  #-----------------------------------------------
  #create global variables
  pdb_str <- NULL
  retrieve_input_pdb <- NULL
  cav_out_names <- NULL
  cav_list <- NULL
  result_toml <- NULL
  protein_rep_list <- c()
  pdb_processed <- NULL
  pdb_ligand_processed <- NULL
  run_mode_list <- c()
  lig_name_list <- c()
  get_run_id <- c()
  run_id_list <- c()
  protein_col_list <- c()
  protein_col_scheme_list <- c()
  current_prot_color <- c()
  current_prot_color_scheme <- c()
  
  current_run_id <- c()
  result_pdb <- c()
  
  include_list <- c()
  get_nonstand <- NULL
  
  pdb_name_click_load <- "init"
  
  scheme_color_list <- list("Residue index" = "residueindex",
                           "Chain ID" = "chainid", 
                           "Hidrophobicity" = "hydrophobicity", 
                           "Secondary Structure" = "sstruc")
  #---------------------------------------------
  
  
  #Point to KV help page when click in "More" button in main page 
  observeEvent(input$more_button,{
    updateTabItems(session = session, inputId = "sidebarmenu", selected = "help_kv_sidebar") 
  })
  
  #Create a list of lig names obtained from lig_name text box to guarantee that user will always reload the input input if changes the lig name
  observeEvent(input$lig_name, { #
    lig_name_list <<- c(lig_name_list,input$lig_name)
  })
  
  #------------------------------------------------------
  #Upload PDB section 
  observeEvent(input$input_pdb, {
    process_upload(input = input, output = output)
    
    #run_mode_list <<- c()
    #lig_name_list <<- c()

  #   if(input$run_mode == "lig_mode"){
  #     #process PDB according to ligand mode
  #     process_upload_ligmode(input = input, output = output)
  #   } else { #not ligand mode
  #     #process PDB according to all the other modes: default, customized and box mode.
  #     process_upload(input = input, output = output)
  #   }
  #   
   })
  #-----------------------------------------------------
  
  #-----------------------------------------------------
  #Fetch PDB section
  observeEvent(input$send_pdb_id, {
    #run_mode_list <<- c()
    #lig_name_list <<- c()
    pdb_name_click_load <<- input$pdb_id
    
    #check if the PDB code is valid by using get_nonstand  
    showModal(modalDialog("Loading and checking PDB...", footer=NULL,fade = FALSE))
    get_nonstand_check <- report_nonstand(pdb_input = input$pdb_id)
    removeModal()
    if (is.na(get_nonstand_check)){
      shinyalert("Oops!", "Please insert a valid PDB ID.", type = "error")
    } else{
      print("PDB ID ok")
    }
    
    process_fetch(input = input, output = output)
    
    # if(input$run_mode == "lig_mode"){
    #   #process PDB according to ligand mode
    #   process_fetch_ligmode(input = input, output = output)
    # } else { #not ligand mode
    #   #process PDB according to all the other modes: default, customized and box mode.
    #   process_fetch(input = input, output = output)
    # }
  })
  
  #----------------------------------------------------
  #Submit section
  observeEvent(input$submit_button, {
      # Create modal dialog
      showModal(modalDialog("Submitting...", footer=NULL,fade = FALSE))
      #create a temporary empty ui output for NGL visualization and status card 
      #this is necessary to avoid the previous state (hidden by hideElement) to be shown when running showElement function
      output[["structure"]] <- renderNGLVieweR({}) 
      output[["output_status1"]] <- NULL
      

      # Get current id
      current_run_id <<- submit_job(input = input, 
                                   output = output,
                                   pdb_name_click_load = pdb_name_click_load)
      removeModal()
      # If result_pdb object is not null, i.e. the Check button was clicked previously, 
      # all the buttons generated by Check results, will be hided. 
      if(!is.null(result_pdb)){
        hideElement(
          id = "download",
          time = 0
        )
        hideElement(
          id = "download2",
          time = 0
        )
        hideElement(
          id = "view_str",
          time = 0
        )
        hideElement(
          id = "table_out",
          time = 0
        )

        hideElement(
          id = "output_status1",
          time = 0
        )
        hideElement(
          id = "structure",
          time = 0
        )
        hideElement(
          id = "selection_pdb",
          time = 0
        )
        hideElement(
          id = "cavity_color",
          time = 0
        )
        hideElement(
          id = "protein_rep",
          time = 0
        )
        hideElement(
          id = "protein_color",
          time = 0
        )
        hideElement(
          id = "protein_color_scheme",
          time = 0
        )
        hideElement(
          id = "show_interface",
          time = 0
        )
        hideElement(
          id = "bg_color",
          time = 0
        )
        hideElement(
          id = "snapshot",
          time = 0
        )
        hideElement(
          id = "snapshot_title",
          time = 0
        )

      }

  })
  #----------------------------------------------------
    
  #----------------------------------------------------
  #>>>>>>>>>>>>>> Check Results <<<<<<<<<<<<<<<<<<<<<<<
  
  #Check results in Run KVFinder page
  observeEvent(input$go_to_check_results, {
    # Run results checking 
    result_pdb <<- check_results(input = input, output = output, run_id = current_run_id, is_pg2 = FALSE)
    # If result_pdb object is not null, i.e. the Check button was clicked in another previous run 
    # The function showElement is executed to show the output status that was hided by the submission button. 
    if(!is.null(result_pdb)){
      showElement(
        id = "output_status1",
        anim = FALSE,
        animType = "slide",
        time = 0,
        selector = NULL,
        asis = FALSE
      )
    }
    # Create a 'observe' to monitor the results checking and automatically update the status each 5s when in queued or running
    observe({
      result_pdb <<- check_results(input = input, output = output, run_id = current_run_id, is_pg2 = FALSE)
      if(result_pdb %in% c("queued", "running")){
        invalidateLater(5000)
      } else{ #in case of status completed or error, the check_results will not be updated each 5s
        # the hided elements are also showed
        showElement(
          id = "download",
          time = 0
        )
        showElement(
          id = "download2",
          time = 0
        )
      }
    })
    #disable button 
    disable("go_to_check_results")
  })
  

  observeEvent(input$check_loc_pg2, {
    #output[["structure_p2"]] <<- NULL
    result_pdb <<- check_results(input = input, output = output, run_id = input$insert_ID, is_pg2 = TRUE)
    # When check results button in page 2 is clicked, the structure visualization and all buttons related to NGL viewer are hided
    # to allow an updated if the check button is used other times
    output[["structure_pg2"]] <- renderNGLVieweR({}) 
    hideElement(
      id = "structure_pg2",
      time = 0
    )
    hideElement(
      id = "selection_pdb_pg2",
      time = 0
    )
    hideElement(
      id = "cavity_color_pg2",
      time = 0
    )
    hideElement(
      id = "protein_rep_pg2",
      time = 0
    )
    hideElement(
      id = "protein_color_pg2",
      time = 0
    )
    hideElement(
      id = "protein_color_scheme_pg2",
      time = 0
    )
    hideElement(
      id = "show_interface_pg2",
      time = 0
    )
    hideElement(
      id = "bg_color_pg2",
      time = 0
    )
    hideElement(
      id = "snapshot_pg2",
      time = 0
    )
    hideElement(
      id = "snapshot_title_pg2",
      time = 0
    )
  })
  #----------------------------------------------------
  
  #----------------------------------------------------
  #>>>>>Visualize 3D results using NGLVieweR<<<<<<<<<<<
  
  #View in Run KVFinder main page
  
  #Click view to visualize
  observeEvent(input$view_str, {
    print("inside_view_str")

    protein_rep_list <<- c() #always zero rep list when click view
    protein_col_scheme_list <<- c() #always zero color scheme list when click view
    #current states
    protein_col_scheme_list <<- c(protein_col_scheme_list, "Residue index")
    #protein_col_list <<- c(protein_col_list, "white")
    #Create initial scene
    create_init_scene(input = input, output = output, result_pdb_list = result_pdb, is_pg2 = FALSE)
    # Show all elements that were hided
    showElement(
      id = "structure",
      time = 0
    )
    showElement(
      id = "selection_pdb",
      time = 0
    )
    showElement(
      id = "cavity_color",
      time = 0
    )
    showElement(
      id = "protein_rep",
      time = 0
    )
    showElement(
      id = "protein_color",
      time = 0
    )
    showElement(
      id = "protein_color_scheme",
      time = 0
    )
    showElement(
      id = "show_interface",
      time = 0
    )
    showElement(
      id = "bg_color",
      time = 0
    )
    showElement(
      id = "snapshot",
      time = 0
    )
    showElement(
      id = "snapshot_title",
      time = 0
    )
    
    # current_rep <- input$input_protein_rep
    # protein_rep_list <<- c(protein_rep_list, current_rep)
    # #Create a work scene
    # create_work_scene(input = input, output = output, protein_rep_list = protein_rep_list, protein_col_list = protein_col_list, protein_col_scheme_list = protein_col_scheme_list, result_pdb_list = result_pdb, is_pg2 = FALSE)
    
    disable("view_str")
  }, ignoreInit = FALSE, ignoreNULL = TRUE)
  
  #Create a work scene and change biomolecular structure representation 
  observeEvent(input$input_protein_rep,{
    print("observe_protein_rep")
    #print(input$input_protein_rep)
    #save the current representation
    current_rep <- input$input_protein_rep
    print(current_rep)
    #create a list of representations 
    protein_rep_list <<- c(protein_rep_list, current_rep)
    #Create a work scene
    create_work_scene(input = input, output = output, protein_rep_list = protein_rep_list, protein_col_list = protein_col_list, protein_col_scheme_list = protein_col_scheme_list, result_pdb_list = result_pdb, is_pg2 = FALSE)
    
    #clean protein color selector
    updateSelectInput(session,'input_protein_color', #This update is made to clean the protein color selector
                      # choices = c("","white", "red", "blue", "green","yellow"),
                      selected = '')
  }, ignoreNULL = TRUE, ignoreInit = TRUE)
  #Select cavity to be visualized 
  observeEvent(input$select_cavity, {
    select_cav(input = input, output = output, result_pdb_list = result_pdb, is_pg2 = FALSE)
  })
  #change biomolecular structure color
  #print("hereCOlor")
  
  observeEvent(input$input_protein_color, {
    #if(length(input$input_protein_color) > 1){ #only change protein color if we change the input color
      protein_col_list <<- change_str_color(input = input, output = output, protein_col_list = protein_col_list, is_pg2 = FALSE) 
    #}
  })
  #change biomolecular structure color
  observeEvent(input$input_protein_color_scheme, {
    #print("hereScheme")
    protein_col_scheme_list <<- change_str_color_scheme(input = input, output = output, protein_col_scheme_list = protein_col_scheme_list,protein_rep_list = protein_rep_list, is_pg2 = FALSE)
    #print(protein_col_scheme_list)
    updateSelectInput(session,'input_protein_color',
                     # choices = c("","white", "red", "blue", "green","yellow"),
                      selected = '')
  },ignoreNULL = TRUE)
  #change cavity color
  observeEvent(input$input_cavity_color, {
    #print("cavColor")
    change_cav_color(input = input, output = output, is_pg2 = FALSE)
  })
  #change background color
  observeEvent(input$input_bg_color, {
    change_bg_color(input = input, output = output, is_pg2 = FALSE)
  })
  #take a snapshot
  observeEvent(input$input_snapshot, {
    take_snapshot(input = input, output = output, is_pg2 = FALSE)
  })
  
  ##### View in Get latest results page (pg2)
  
  #Click view to visualize
  observeEvent(input$view_str_pg2, {
    protein_rep_list <<- c() #always zero rep list when click view
    protein_col_list <<- c(protein_col_list, "residueindex")
    #protein_col_scheme_list <<- c(protein_col_scheme_list, "white")
    
    #Create initial scene
    create_init_scene(input = input, output = output, result_pdb_list = result_pdb, is_pg2 = TRUE)
    # Show visualization states and buttons if they are hided by the previous results checking
    showElement(
      id = "structure_pg2",
      time = 0
    )
    showElement(
      id = "selection_pdb_pg2",
      time = 0
    )
    showElement(
      id = "cavity_color_pg2",
      time = 0
    )
    showElement(
      id = "protein_rep_pg2",
      time = 0
    )
    showElement(
      id = "protein_color_pg2",
      time = 0
    )
    showElement(
      id = "protein_color_scheme_pg2",
      time = 0
    )
    showElement(
      id = "show_interface_pg2",
      time = 0
    )
    showElement(
      id = "bg_color_pg2",
      time = 0
    )
    showElement(
      id = "snapshot_pg2",
      time = 0
    )
    showElement(
      id = "snapshot_title_pg2",
      time = 0
    )
    disable("view_str_pg2")
  })
  
  
  
  #Create a work scene and change biomolecular structure representation 
  observeEvent(input$input_protein_rep_pg2,{
    #save the current representation
    current_rep <- input$input_protein_rep_pg2
    #create a list of representations 
    protein_rep_list <<- c(protein_rep_list, current_rep)
    #Create work scene
    create_work_scene(input = input, output = output, protein_rep_list = protein_rep_list, protein_col_list = protein_col_list, protein_col_scheme_list = protein_col_scheme_list, result_pdb_list = result_pdb, is_pg2 = TRUE)
    
    #clean protein color selector
    updateSelectInput(session,'input_protein_color_pg2', #This updation is made to clean the protein color selector 
                      # choices = c("","white", "red", "blue", "green","yellow"),
                      selected = '') 
  }, ignoreNULL = TRUE, ignoreInit = FALSE)
  #Select cavity to be visualized
  observeEvent(input$select_cavity_pg2, {
    select_cav(input = input, output = output, result_pdb_list = result_pdb, is_pg2 = TRUE)
  })
    #change biomolecular structure color
    observeEvent(input$input_protein_color_pg2, {
    protein_col_list <<- change_str_color(input = input, output = output, protein_col_list = protein_col_list, is_pg2 = TRUE)
    }, ignoreInit = F, ignoreNULL = T)
    #change biomolecular structure color
    observeEvent(input$input_protein_color_scheme_pg2, {
      protein_col_scheme_list <<- change_str_color_scheme(input = input, output = output, protein_col_scheme_list = protein_col_scheme_list, is_pg2 = TRUE)
      updateSelectInput(session,'input_protein_color_pg2', #This updation is made to clean the protein color selector 
                        # choices = c("","white", "red", "blue", "green","yellow"),
                        selected = '') 
    })
    #change cavity color
    observeEvent(input$input_cavity_color_pg2, {
    change_cav_color(input = input, output = output, is_pg2 = TRUE)
    })
    #change background color
    observeEvent(input$input_bg_color_pg2, {
    change_bg_color(input = input, output = output, is_pg2 = TRUE)
    })
    #take a snapshot
    observeEvent(input$input_snapshot_pg2, {
    take_snapshot(input = input, output = output, is_pg2 = TRUE)
    })

  #----------------------------------------------------
  
  
}
